
name: Deploy fastapi

on:
  push:
    branches: [main]
    paths: ['**']

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker image
      uses: docker/build-push-action@v6
      with:
        context: ./project
        file: ./project/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/epita-mlops-fastapi:latest

  build-and-deploy:
    runs-on: emre-eu
    permissions:
      contents: read
      packages: write
    steps:
    - name: Deploy to eu-fastapi
      run: |
        cd /home/ubuntu/eu/epita_mlops/project
        git reset --hard HEAD
        git clean -fd
        git fetch origin
        git reset --hard origin/main
        git pull
        docker compose up -d --build